In [ ]:
#Basic if else statement
#1.Write a python program to check if a given number is positive or negative                                                                                                                                               #1. Write a python program to check if a given number is positive or negative

num = 0
if num >= 0:
  print("Number is positive")
else:
  print("Number is negative")

Number is positive


In [ ]:
#2. Create a program that determines if a person is eligible to vote based on their age

voters_age = 19
if voters_age >= 18:
  print("Voter is eligible to vote")
else:
  print("Voter is not eligible to vote")

Voter is eligible to vote


In [ ]:
#3. Develop a program to find the maximum of two numbers using if-else statements

def maximum(a,b):
  if a >= b:
    return a
  else:
    return b
a = 2
b = 4
print(maximum(a,b))

4


In [ ]:
#4. Write a python script to classify a given year as a leap year or not

def checkYear(year):
  import calendar
  return(calendar.isleap(year))
year = 2000
if(checkYear(year)):
  print("Leap Year")
else:
  print("Not a Leap Year")

Leap Year


In [ ]:
#5. Create a program that checks whether a character is a vowel or a consonent

def vowelOrConsonant(x):
  if(x =='a' or x == 'e' or x == 'i' or x == 'o' or x == 'u'):
    print("Vowel")
  else:
    print("Consonant")
vowelOrConsonant('c')
vowelOrConsonant('e')

Consonant
Vowel


In [ ]:
#6. Implement a program to determine whether a given number is a even is even or odd

num = int(input("Enter a number: "))
if(num %2 == 0):
  print("{0} is Even number".format(num))
else:
  print("{0} is Odd number".format(num))

Enter a number: 9
9 is Odd number


In [ ]:
#7. Write a python function to calculate the absolute value of a number without using the'abs' function

def absolute_value(num):
  if num >= 0:
    return num
  else:
    return -num
print(absolute_value(10))
print(absolute_value(-20))
print(absolute_value(0))

10
20
0


In [18]:
#8. Develop a program that determines the largest of 3 given numbers using if-else statements

num1 = 25
num2 = 30
num3 = 20
if (num1 >= num2) and (num1 >= num3):
  largest = num1
elif (num2 >= num1) and (num2 >= num3):
  largest = num2
else:
  largest = num3
print("The largest number is", largest)

The largest number is 30


In [ ]:
#9. Create a program that checks if a given string is a palindrome

def isPalindrome(s):
  return s == s[::-1]
s = "malayalam"
ans = isPalindrome(s)
if ans:
  print("Yes")
else:
  print("No")

Yes


In [ ]:
#10. Write a python program to calculate the grade based on a student's score

marks = float(input("Enter the number "))
if (marks < 40):
  print("Satisfactory")
elif(marks > 40 and marks < 80):
  print("Good")
else:
  print("Excellent")

Enter the number 88
Excellent


In [ ]:
# Nested if else statement
#11. Write a program to find the largest among three numbers using nested-if else statements

a = int(input("Enter A: "))
b = int(input("Enter B: "))
c = int(input("Enter C: "))
if a>b:
  if a>c :
    g=c
else:
  if b>c:
    g=b
  else:
      g=c
print("Greater =" , g)

Enter A: 10
Enter B: 20
Enter C: 5
Greater = 20


In [ ]:
#12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene

def checkTriangle(x,y,z):
  if x == y == z:
    print("Equilateral triangle")
  elif x == y or y == z or z == x:
    print("Isosceles Triangle")
  else:
    print("Scalene Triangle")
x = 8
y = 7
z = 9
checkTriangle(x,y,z)

Scalene Triangle


In [ ]:
#13. Develop a program that checks if a year is a leap year and also if it is a century year

def checkYear(year):
  import calendar
  return(calendar.isleap(year))
year = 2000
if(checkYear(year)):
  print("Leap Year")
else:
    print("Not a Leap Year")

Leap Year


In [ ]:
#14. Write a python script to determine if a number is a positive, negative or zero

def NumberCheck(a):
  if a > 0:
    print("Number is positive")
  elif a < 0:
    print("Number is negative")
  else:
    print("Number is zero")
a = int(input("Enter a number: "))
NumberCheck(a)

Enter a number: -6
Number is negative


In [ ]:
#15. Create a program to check if a person is a teenager(between 13 to 19 yrs old)

age = int(input("Enter your age: "))
if(age > 18):
  print("Eligible to vote")
else:
  print("Not eligible to vote")

Enter your age: 14
Not eligible to vote


In [ ]:
#16. Develop a program that determines the type of angle based on its measure(acute, obtuse or right)

a = int(input("Enter the number of 1: "))
b = int(input("Enter a number of 2: "))
c = int(input("Enter a number of 3: "))
if(a+b+c <= 90):
  print("Acute Angle")
if(90>a<=180 or 90>b<=180 or 90>c<=180):
  print("Obtuse Angle")
if(a == 90 or b == 90 or c == 90):
  print("Right Angle")

Enter the number of 1: 90
Enter a number of 2: 30
Enter a number of 3: 10
Obtuse Angle
Right Angle


In [ ]:
#17. Write a python program to calculate the roots of a quadratic equation

import cmath
a = 1
b = 4
c = 2
dis = (b**2) -(4*a*c)
ans1 = (-b-cmath.sqrt(dis))/(2*a)
ans2 = (-b + cmath.sqrt(dis))/(2*a)
print('The roots are')
print(ans1)
print(ans2)

The roots are
(-3.414213562373095+0j)
(-0.5857864376269049+0j)


In [ ]:
#18. Implement a program to determine the day of the week based on a user-provided number(1 for monday, 2 for tuesday, etc)

day = int(input("Enter a number from 1 to 7: "))
if day == 1:
  print(day, "is Sunday")
elif day == 2:
  print(day, "is Monday")
elif day == 3:
  print(day, "is Tuesday")
elif day == 4:
  print(day, "is Wednesday")
elif day == 5:
  print(day, "is Thurday")
elif day == 6:
  print(day, "is Friday")
elif day == 7:
  print(day, "is Saturday")
else:
  print("Wrong input! Please enter a correct number")

Enter a number from 1 to 7: 3
3 is Tuesday


In [ ]:
#19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400

def ISLP(y):
 if ((y % 400 == 0) or
     (y % 100 != 0) and
     (y % 4 == 0)):
    return 1;
 else:
    return 0;
if __name__ == '__main__':
  year = 2020;
  print(ISLP(year));

1


In [ ]:
#20. Develop a program that checks if a given number is prime or not using nested if-else statements

num= 11
if num > 1:
  for i in range(2, int (num/2) + 1):
    if(num % i) == 0:
      print(num, "is not a primt number")
      break
  else:
      print(num, "is a prime number")
else:
   print(num, "is not a prime number")

11 is a prime number


In [ ]:
# Elif Statements
#21. Write a python program to assign grades based on different ranges of sources using elif statements

print("Enter Marks Obtained  in 5 subjects: ")
total1 = 44
total2 = 67
total3 = 76
total4 = 99
total5 = 58
tot = total1 + total2 + total3 + total4 + total5
avg = tot / 5
if avg >= 91 and avg <= 100:
  print("Your Grade is A1")
elif avg >= 81 and avg < 91:
  print("Your Grade is A2")
elif avg >= 71 and avg < 81:
  print("Your Grade is B1")
elif avg >= 61 and avg < 71:
  print("Your Grade is B2")
elif avg >= 51 and avg < 61:
  print("Your Grade is C1")
elif avg >= 41 and avg < 51:
  print("Your Grade is C2")
elif avg >= 33 and avg < 41:
  print("Your Grade is D")
elif avg >= 21 and avg < 33:
  print("Your Grade is E1")
elif avg >= 0 and avg < 21:
  print("Your Grade is E2")
else:
  print("Invalid Input")

Enter Marks Obtained  in 5 subjects: 
Your Grade is B2


In [ ]:
#22. Implement a program to determine the type of triangle based on its angles

def checkTriangle(x,y,z):
  if x == y == z:
    print("Equilateral Triangle")
  elif x == y or y == z or z == x:
    print("Isosceles Triangle")
  else:
    print("Scalene Triangle")
x = 8
y = 7
z = 9
checkTriangle(x,y,z)

Scalene Triangle


In [ ]:
#23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using elif statements

h = float(input("Enter your height in meters: "))
w = float(input("Enter your weight in kg: "))
BMI = w/(h * h)
print("BMI calculated is: ", BMI)
if(BMI > 0):
  if(BMI <= 16):
    print("You are very underweight")
  elif(BMI <=  18.5):
    print("You are underweight")
  elif(BMi <= 25):
    print("Congrats! You are healthy")
  elif(BMI <= 30):
    print("You are overweight")
  else:
    print("You are very overweight")
else:
  print("Enter valid details")

Enter your height in meters: 6.4
Enter your weight in kg: 34
BMI calculated is:  0.8300781249999999
You are very underweight


In [ ]:
#24. Create a program that determines whether a given number is positive, negative, or zero using elif statements

num = float(input("Input a number: "))
if num > 0:
  print("It is a positive number")
elif num == 0:
  print("It is a zero")
else: print("It is neagative number")

Input a number: 0
It is a zero


In [ ]:
#25. Write a python script to determine the type of a character(uppercase, lowercase,or special) using elif statements

ch = input("Enter a character: ")
if(ch.isupper()):
  print("Its an uppercase chracter")
elif(ch.islower()):
  print("Its a lowercase")
else:
  print("Its a special character")

Enter a character: L
Its an uppercase chracter


In [ ]:
#26. Implement a program to calculate the discounted price based on different purchase amounts using elif statements

def discountPercentage(S,M):
   discount = M - S
   disPercent = (discount / M) * 100
   return disPercent
if __name__ == '__main__':
  M = 120
  S = 100
  print(discountPercentage(S, M), "%")
  M= 1000
  S = 500
  print(discountPercentage(S, M), "%")

16.666666666666664 %
50.0 %


In [ ]:
#27. Develop a program to calculate the electricity bill based on different consumption slabs using elif statements

def calculateBill(units):
  if(units <= 100):
    return units * 10;
  elif (units <= 200):
    return((100 * 10) + (units - 100) * 15);
  elif(units <= 300):
    return((100 * 10) + (100 * 15) + (units - 200) * 20);
  elif(units > 300):
    return((100 * 10) + (100 * 15) + (units - 300) * 25);
  return 0;
units = 250
print(calculateBill(units));

3500


In [ ]:
#28. Create a program to determine the type of quadrilateral based on its angles and sides using elif statements

d = 10
a = 0.0
a = (360 - (6 * d)) / 4
print(a,",", a + d, ",", a + 2 * d, ",", a + 3 * d, sep = ' ')

75.0 , 85.0 , 95.0 , 105.0


In [ ]:
#29. Write a pyhton script to determine the season based on a user-provided month using elif statements

def findseason(M):
  list1 = [[12, 1 , 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]
  if M in list1[0]:
    print("Winter")
  elif M in list1[1]:
    print("Spring")
  elif M in list1[2]:
    print("Summer")
  elif M in list1[3]:
    print("Autumn")
  else:
    print("Invalid Month Number")
M = 5
print("For Month number:", M)
findseason(M)

For Month number: 5
Spring


In [17]:
#30. Implement a program to determine the type of a year(leap or common) and month (30 or 31 days)using elif statements

def ISLP(y):
  if((y % 400 == 0) or (y % 100 != 0) and (y % 4 == 0)):
    return 1
  else:
    return 0
if __name__ == '__main__':
  year = 2020
  print(ISLP(year))

1


In [ ]:
#Basic Level
#1. Write a python program that checks if a given number is positive, negative, or zero

num = float(input("Enter a number: "))
if num > 0:
  print("Positive number")
elif num == 0:
  print("Zero")
else:
  print("Negative number")

Enter a number: 7
Positive number


In [ ]:
#2. Create a program to determine if a person is eligible to vote based on their age

age = int(input("Enter your age: "))
if age >= 18:
  print("You are eligible to vote.")
else:
  print("You are not eligible to vote.")

Enter your age: 65
You are eligible to vote.


In [ ]:
#3. Write a program to find the maximum of two given numbers using conditional statements

a = 2 ; b = 4
maximum = lambda a, b:a if a > b else b
print(f'{maximum(a,b)} is a maximum number')

4 is a maximum number


In [ ]:
#4. Develop a program that calculates the grade of a student based on their exam score

score = float(input("Enter your score: "))
if(score >= 90):
 print("Very Good")
elif(score >= 60):
 print("Good")
elif(score <= 40):
 print("Satisfactory")
else:
  print("Need to work hard")

Enter your score: 99
Very Good


In [ ]:
#5. Create a program that checks if a year is a leap year or not

year = int(input("Enter year to be checked: "))
if(year %4 == 0 and year %100!= 0 or year % 400 == 0):
  print("The year is a leap year")
else:
  print("The year is not a leap year")

Enter year to be checked: 2016
The year is a leap year


In [ ]:
#6. Write a program to classify a triangle based on its sides lengths

def checkTriangle(x, y, z):
  if x == y == z:
    print("Equilateral Triangle")
  elif x== y or y == z or z == x:
    print("Isosceles Triangle")
  else:
    print("Scalene Triangle")
x = 8
y = 7
z = 9
checkTriangle(x, y, z)

Scalene Triangle


In [ ]:
#7. Build a program that determines the largest of three given numbers

def maximum(a, b, c):
  list = [a, b, c]
  return max(list)
a = 10
b = 14
c = 12
print(maximum(a, b, c))

14


In [ ]:
#8. Develop a program that checks whether a character is a vowel or a consonant

def vowelOrConsonant(x):
  if(x =='a' or x == 'e' or x == 'i' or x == 'o' or x == 'u'):
    print("Vowel")
  else:
    print("Consonant")
vowelOrConsonant('f')
vowelOrConsonant('i')

Consonant
Vowel


In [ ]:
#9. Create a program to calculate the total cost of a shopping cart based on discounts

drinks = input("How many drinks do you want? ")
drinks = int(drinks)
total = 0
single = 2.25
six = 10
sixPacks = drinks // 6
singles = drinks % 6
total += six * sixPacks
total += single * singles
if total > 20:
  total *= 0.75
print("That will be a total of: {} dollars.format(round(total, 2))")

How many drinks do you want? 6
That will be a total of: {} dollars.format(round(total, 2))


In [ ]:
#10. Write a program that checks if a given number is even or odd

def evenOdd(n):
  if(n == 0):
    return True
  elif(n == 1):
    return False
  else:
    return evenOdd(n - 2)
num = 33
if(evenOdd(num)):
  print(num,"num is even")
else:
  print(num,"num is odd")

33 num is odd


In [ ]:
#Imtermediate Level
#11. Write a program that calculates the roots of a quadratic equation

import cmath
a = 1
b = 4
c = 2
dis = (b ** 2) - (4 * a * c)
ans1 = (-b-cmath.sqrt(dis))/(2 * a)
ans2 = (-b + cmath.sqrt(dis))/(2 * a)
print('The roots are')
print(ans1)
print(ans2)

The roots are
(-3.414213562373095+0j)
(-0.5857864376269049+0j)


In [ ]:
#12. Create a program that determines the day of the week based on the day number

import datetime
import calendar
def findDay(date):
  born = datetime.datetime.strptime(date, '%d %m %Y').weekday()
  return (calendar.day_name[born])
date = '03 02 2019'
print(findDay(date))

Sunday


In [ ]:
#13. Develop a program that calculates the factorial of a given number using recursion

def recursive_factorial(n):
  if n == 1:
    return n
  else:
    return n*recursive_factorial(n - 1)
number = int(input("User Input: "))
print("The factorial of", number, "is", recursive_factorial(number))

User Input: 5
The factorial of 5 is 120


In [ ]:
#14. Write a program to find the largest three numbers without using the 'max' function

def maximum(a, b, c):
  if(a >= b) and (a >= c):
    largest = a
  elif (b >= a) and (b >= c):
    largest = b
  else:
    largest = c
  return largest
a = 10
b = 14
c = 12
print(maximum(a, b, c))

14


In [ ]:
#15. Create a program that simulates a basic ATM transaction menu

class Bank_Account:
  def __init__(self):
    self.balance = 0
    print("Hello!!! Welcome to the Deposit & Withdrawal Machine")
  def deposit(self):
    amount = float(input("Enter amount to be Deposited: "))
    self.balance += amount
    print("\n Amount Deposited: ", amount)
  def withdraw(self):
    amount = float(input("Enter amount to be Withdrawn: "))
    if self.balance >= amount:
       self.balance -= amount
       print("\n You Withdrew: ", amount)
    else:
      print("\n Insufficient Balance ")
  def display(self):
    print("\n Net AvailableBalance =", self.balance)
s = Bank_Account()
s.deposit()
s.withdraw()
s.display()

Hello!!! Welcome to the Deposit & Withdrawal Machine
Enter amount to be Deposited: 1000

 Amount Deposited:  1000.0
Enter amount to be Withdrawn: 1500

 Insufficient Balance 

 Net AvailableBalance = 1000.0


In [ ]:
#16. Build a program that checks if a given string is a palindrome or not

def isPalindrome(s):
  return s == s[::-1]
s = "madam"
ans = isPalindrome(s)
if ans:
  print("Yes")
else:
  print("No")

Yes


In [ ]:
#17. Write a program that calculates the average of a list of numbers ,excluding the smallest and largest values

def average(arr, n, k):
  total = 0
  if(1 * k >= n):
    return 0
  arr.sort()
  start, end = k , n - k - 1
  for i in range(start, end + 1):
    total += arr[i]
    return(total / (n - 1 * k))
if __name__ == '__main__':
  arr = [1, 2, 4, 4, 5, 6]
  n = len(arr)
  k = 1
  print(average(arr, n, k))

0.4


In [ ]:
#18. Develop a program that converts a given temperature from celsius to fahrenheit

celsius = float(input("Enter temperature in celsius: "))
fahrenheit = (celsius * 1.8) + 32
print(str(celsius)+ " degree Celsius is equal to " + str(fahrenheit) + " degree Fahrenheit")

Enter temperature in celsius: 40
40.0 degree Celsius is equal to 104.0 degree Fahrenheit


In [ ]:
#19. Create a program thta simulates a basic calculator for addition, subtraction, multiplication,and division

def add(num1, num2):
  return num1 + num2
def subtract(num1, num2):
  return num1 - num2
def multiply(num1, num2):
  return num1 * num2
def divide(num1, num2):
  return num1 / num2
print("Please select operation -\n" \
      "1. Add\n" \
      "2. Subtract\n" \
      "3. Multiply\n" \
      "4. Divide\n")
select = int(input("Select operations from 1, 2, 3, 4: "))
number_1 = int(input("Enter first number: "))
number_2 = int(input("Enter second number: "))
if select == 1:
  print(number_1, "+", number_2, "=", add(number_1, number_2))
elif select == 2:
  print(number_1, "-", number_2, "=", subtract(number_1, number_2))
elif select == 3:
  print(number_1, "*", number_2, "=", multiply(number_1, number_2))
elif select == 4:
  print(number_1, "/", number_2, "=", divide(number_1, number_2))
else:
  print("Invalid input")

Please select operation -
1. Add
2. Subtract
3. Multiply
4. Divide

Select operations from 1, 2, 3, 4: 4
Enter first number: 24
Enter second number: 2
24 / 2 = 12.0


In [ ]:
#20. Write a program that determines the roots of a cubic equation using the Cardano formula

from functools import reduce
def cubic_roots(n):
  x = n
  y = (2 * x + n / x ** 2) / 3
  while abs(x - y) >= 0.000001:
    x = y
    y = reduce(lambda a, b: (2 * a + n / b ** 2) / 3, [y, y])
  return y
n = 3
print("Cubic root of", n, "is", round(cubic_roots(n), 6))

Cubic root of 3 is 1.44225


In [ ]:
#Advanced level
#21. Create a program that calculates the income tax based on the user's income and tax brackets

def calculate(amount, percent):
  return(amount * percent) / 100
def calculate_income_tax(total_income:float) :
  if total_income <= 250000:
    return 0
  elif total_income <= 500000:
    return calculate(total_income - 250000, 5)
  elif total_income <= 750000:
    return calculate(total_income - 500000, 10) + 12500
  elif total_income <= 1000000:
    return calculate(total_income - 750000, 15) + 37500
  elif total_income <= 1250000:
    return calculate(total_income - 1000000, 20) + 75000
  elif total_income <= 1500000:
    return calculate(total_income - 1250000, 25) + 125000
  else:
    return calculate(total_income - 1500000, 30) + 187500
if __name__ == '__main__':
  total_income = float(input("What's your annual income? "))
  tax = calculate_income_tax(total_income)
  print(f"Total tax applicable at  {total_income} is {tax}")

What's your annual income? 500000
Total tax applicable at  500000.0 is 12500.0


In [ ]:
#22. Write a program that simulates a rock-paper-scissorsgame against the computer

import random
options = ["Rock", "Paper", "Scissors"]
user_choice = input("Choose Rock, Paper or Scissors: ")
computer_choice = random.choice(options)
print("You chose: ", user_choice)
print("Computer chose: ", computer_choice)
if user_choice == computer_choice:
  print("It's a tie!")
elif user_choice == "Rock" and computer_choice == "Scissors":
  print("You win!")
elif user_choice == "Paper" and computer_choice == "Rock":
  print("You win!")
elif user_choice == "Scissors" and computer_choice == "Paper":
  print("You win!")
else:
  print("Computer wins!")

Choose Rock, Paper or Scissors: paper
You chose:  paper
Computer chose:  Paper
Computer wins!


In [ ]:
#23. Develop a program that generates a random password based on user preferences(length,complexity)

import string
import random
length = int(input("Enter password length: "))
print('''Choose chractre set for password from these:
1. Digits
2. Letters
3. Special characters
4. Exit''')
characterList = ""
while(True):
  choice = int(input("Pick a number "))
  if(choice == 1):
    characterList += string.ascii_letters
  elif(choice == 2):
    characterList += string.digits
  elif(choice == 3):
    characterList += string.punctuation
  elif(choice == 4):
    break
  else:
    print("Please pick a valid option! ")
password = []
for i in range(length):
  randomchar = random.choice(characterList)
  password.append(randomchar)
print("The random password is " + "".join(password))

Enter password length: 10
Choose chractre set for password from these:
1. Digits
2. Letters
3. Special characters
4. Exit
Pick a number 1
Pick a number 4
The random password is rNWthwHNrT


In [ ]:
#24. Create a program that implements a simple text-based adventure game with branching scenarios

import random
name = input("What's is your name? ")
print("Good Luck!", name)
words = ['rainbow', 'computer', 'science', 'programming', 'python', 'mathematics', 'player', 'condition', 'reverse', 'water', 'board']
word = random.choice(words)
print("Guess the characters")
guesses = ''
turns = 5
while turns > 0:
  failed = 0
  for char in word:
    if char in guesses:
       print(char, end = " ")
    else:
       print("_")
       failed += 1
  if failed == 0:
    print("You Win")
    print("The word is: ", word)
    break
  print()
  guess = input("Guess a character: ")
  guesses += guess
  if guess not in word:
    turns -= 1
    print("Wrong")
    print("You have", + turns, 'more guesses')
    if turns == 0:
      print("You Loose")

What's is your name? Sanyogita
Good Luck! Sanyogita
Guess the characters
_
_
_
_
_
_
_
_

Guess a character: c
c _
_
_
_
_
_
_

Guess a character: o
c o _
_
_
_
_
_

Guess a character: m
c o m _
_
_
_
_

Guess a character: p
c o m p _
_
_
_

Guess a character: u
c o m p u _
_
_

Guess a character: 
c o m p u _
_
_

Guess a character: 
c o m p u _
_
_

Guess a character: t
c o m p u t _
_

Guess a character: e
c o m p u t e _

Guess a character: r
c o m p u t e r You Win
The word is:  computer


In [ ]:
#25. Build a program that solves a linear equation for x, considering different cases

from sympy import symbols, Eq, solve
x, y = symbols('x,y')
eq1 = Eq((x + y), 1)
print("Equation 1: ")
print(eq1)
eq2 = Eq((x - y), 1)
print("Equation 2")
print(eq2)
print("Values of 2 unknown variable are as follows: ")
print(solve((eq1, eq2), (x, y)))

Equation 1: 
Eq(x + y, 1)
Equation 2
Eq(x - y, 1)
Values of 2 unknown variable are as follows: 
{x: 1, y: 0}


In [ ]:
#26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring

def check_guess(guess, answer):
  global score
  still_guessing = True
  attempt = 0
  while still_guessing and attempt < 3:
    if guess.lower() == answer.lower():
      print("Correct Answer")
      score = score + 1
      still_guessing = False
    else:
      if attempt < 2:
        guess = input("Sorry Wrong Answer, Try Again ")
      attempt = attempt + 1
  if attempt == 3:
    print("The correct answer is: ", answer)
score = 0
print("Guess the animal ")
guess1 = input("Which bear lives at the Northpole? ")
check_guess(guess1, "Polar Bear")
guess2 = input("Which is the fastest land animal? ")
check_guess(guess2, "Cheetah")
guess3 = input("Which is the largest animal? ")
check_guess(guess3, "Blue Whale")
print("Your score is " + str(score))

Guess the animal 
Correct Answer
Which is the fastest land animal?cheetah
Correct Answer


In [ ]:
#27. Develop a program that determines whether a given year is a prime number or not

num = 2023
if num > 1:
  for i in range(2,int(num/2) + 1):
    if (num % i) == 0:
      print(num, "is not a prime year")
      break
    else:
      print(num, "is a prime year")
else:
  print(num, "is not a prime year")

2023 is a prime year
2023 is a prime year
2023 is a prime year
2023 is a prime year
2023 is a prime year
2023 is not a prime year


In [ ]:
#28. Create a program that sorts three numbers in ascending  order using conditional statements

a = float(input("Enter a: "))
b = float(input("Enter b: "))
c = float(input("Enter c: "))
if a > b:
  a, b = b, a
if a > c:
  a, c = c, a
if b > c:
  b, c = c, b
print(a, "<", b, "<", c)

Enter a: 4.6
Enter b: 3.9
Enter c: 5.5
3.9 < 4.6 < 5.5


In [ ]:
#29. Build a program that determines the roots of a quadratic equation using numerical methods

import cmath
a = float(input("Enter a: "))
b = float(input("Enter b: "))
c = float(input("Enter c: "))
d = (b ** 2) - (4 * a * c)
sol1 = (-b - cmath.sqrt(d))/(2 * a)
sol2 = (-b + cmath.sqrt(d))/(2 * a)
print("The solution are {0} and {1}".format(sol1, sol2))

Enter a: 8
Enter b: 5
Enter c: 9
The solution are (-0.3125-1.0135796712641785j) and (-0.3125+1.0135796712641785j)


In [ ]:
#30. Build a program that calculates the BMI(Body Mass Index) and provides health recommendations based on the user's input

height = float(input("Enter the height in cm: "))
weight = float(input("Enter the weight in kg: "))
BMI = weight/(height/100) ** 2
print("Your Body Mass is", BMI)
if BMI <= 18.5:
  print("OOPs! You are underweight.")
elif BMI <= 24.9:
  print("Awesome! You are healthy.")
elif BMI <= 29.9:
  print("Eeee! You are overweight.")
else:
  print("Seesh! You are close.")

Enter the height in cm: 160
Enter the weight in kg: 61
Your Body Mass is 23.828124999999996
Awesome! You are healthy.


In [ ]:
#Challenging level
#31. Create a program that validates a password based on complexity rules(length,characters,etc)

import re
password = "R@m@_f0rtu9e$"
flag = 0
while True:
  if(len(password)<=8):
    flag = -1
    break
  elif not re.search("[a-z]", password):
    flag = -1
    break
  elif not re.search("[A-Z]", password):
    flag = -1
    break
  elif not re.search("[0-9]", password):
    flag = -1
    break
  elif not re.search("[_@$]", password):
    flag = -1
    break
  elif re.search("\s", password):
    flag = -1
    break
  else:
    flag = 0
    print("Valid password")
    break
if flag == -1:
  print("Not a Valid Password ")

Valid password


In [ ]:
#32. Develop a program that performs matrix addition and subtraction based on user input

import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition of two matrix")
print(np.add(A, B))

import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [ ]:
#33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean algorithm

def gcd(a, b):
  if (a == 0):
    return b
  if (b == 0):
    return a
  if (a == b):
    return a
  if (a > b):
    return gcd(a-b, b)
  return gcd(a, b-a)
a = 98
b = 56
if(gcd(a, b)):
  print('GCD of', a, 'and', b, 'is', gcd(a, b))
else:
  print('not found')

GCD of 98 and 56 is 14


In [ ]:
#34. Build a program that performs matrix multiplication using nested loops and conditional statements

def matrix_multiply_recursive(A, B):
  if len(A[0]) != len(B):
    raise ValueError("Invalid matrix dimensions")
  result = [[0 for j in range(len(B[0]))] for i in range (len(A))]
  def multiply(A, B, result, i, j, k):
    if i >= len(A):
      return
    if j >= len(B[0]):
      return multiply(A, B, result, i+1, 0, 0)
    if k >= len(B):
      return multiply(A, B, result, i, j+1, 0)
    result[i][j] += A[i][k] * B[k][j]
    multiply(A, B, result, i, j, k+1)
  multiply(A, B, result, 0, 0, 0)
  return result
A = [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
B = [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]
result = matrix_multiply_recursive(A, B)
for row in result:
  print(row)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [6]:
#35. Create a program that simulates a basic text-based tic-tac-toe game against the computer

import numpy as np
import random
from time import sleep
def create_board():
  return(np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]]))
def possibilities(board):
  l = []
  for i in range(len(board)):
    for j in range(len(board)):
      if board[i][j] == 0:
        l.append((i, j))
  return(l)
def random_place(board, player):
  selection = possibilities(board)
  current_loc = random.choice(selection)
  board[current_loc] = player
  return(board)
def row_win(board, player):
  for x in range(len(board)):
    win = True
    for y in range(len(board)):
      win = True
      for y in range(len(board)):
        if board[x, y] != player:
          win = False
          continue
      if win == True:
         return(win)
  return(win)
def col_win(board, player):
  for x in range(len(board)):
    win = True
    for y in range(len(board)):
      if board[y][x] != player:
        win = False
        continue
    if win == True:
      return(win)
    return(win)
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
      if board[x, x] != player:
        win = False
    if win:
      return win
    win = True
    if win:
      for x in range(len(board)):
        y = len(board) - 1 - x
        if board[x, y] != player:
          win = False
    return win
def evaluate(board):
  winner = 0
  for player in [1, 2]:
    if (row_win(board, player) or col_win(board, player) or diag_win(board, player)):
      winner = player
  if np.all(board != 0) and winner == 0:
    winner = -1
  return winner
def play_game():
  board, winner, counter = create_board(), 0, 1
  print(board)
  sleep(2)
  while winner == 0:
    for player in [1, 2]:
      board = random_place(board, player)
      print("Board after " + str(counter) + "move")
      print(board)
      sleep(2)
      counter += 1
      winner = evaluate(board)
      if winner != 0:
        break
  return(winner)
print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1move
[[0 0 0]
 [0 0 0]
 [1 0 0]]
Board after 2move
[[0 0 0]
 [0 2 0]
 [1 0 0]]
Board after 3move
[[0 0 0]
 [1 2 0]
 [1 0 0]]
Board after 4move
[[0 0 0]
 [1 2 2]
 [1 0 0]]
Board after 5move
[[1 0 0]
 [1 2 2]
 [1 0 0]]
Winner is: 1


In [7]:
#36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods

def fibonacci(n):
  if(n == 0):
    return 0
  else:
    x = 0
    y = 1
    for i in range(1, n):
      z = (x + y)
      x = y
      y = z
      return y
for i in range(10):
  print(fibonacci(i))

0
None
1
1
1
1
1
1
1
1


In [14]:
#37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization

cache = {0:0, 1:1}
def fibonacci_of(n):
  if n in cache:
     return cache[n]
  cache[n] = fibonacci_of(n - 1) + fibonacci_of(n - 2)
  return cache[n]
[fibonacci_of(n) for n in range(15)]

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]

In [ ]:
#38. Create a program that generates a calendar for a given month and year using conditional statements

mm = 2
yy = 2020
month = {1:'January', 2:'February', 3:'March', 4:'April', 5:'May', 6:'June', 7:'July', 8:'August', 9:'September', 10:'October', 11:'November', 12:'December'}
day = (yy - 1) % 400
day = (day//100) * 5 + ((day % 100) - (day % 100)//4) + ((day % 100)//4)*2
day = day % 7
nly = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
ly = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
s = 0
if yy % 4 == 0:
  for i in range(mm - 1):
    s += ly[i]
else:
  for i in range(mm - 1):
    s += nly[i]
day += s % 7
day = day % 7
space = ''
space = space.rjust(2, ' ')
print(month[mm], yy)
print('Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa')
if mm == 9 or mm == 4 or mm == 6 or mm == 11:
  for i in range(31 + day):
    if i <= day:
      print(space, end = ' ')
    else:
      print("{:02d}".format(i - day), end = ' ')
      if (i + 1) % 7 == 0:
        print()
elif mm == 2:
    if yy % 4 == 0:
        p = 30
    else:
        p = 29
    for i in range(p + day):
          if i <= day:
            print(space, end = ' ')
          else:
            print("{:02d}".format(i - day), end = ' ')
            if(i + 1) % 7 == 0:
              print()
else:
  for i in range(32 + day):
    if i <= day:
      print(space, end = ' ')
    else:
      print("{:02d}".format(i-day), end = ' ')
      if (i + 1) % 7 == 0:
        print()

February 2020
Su Mo Tu We Th Fr Sa
                  01 
02 03 04 05 06 07 08 
09 10 11 12 13 14 15 
16 17 18 19 20 21 22 
23 24 25 26 27 28 29 


In [ ]:
#39. Build a program that simulates a basic text-based blackjack game against the computer

import random
card_categories = ['Hearts', 'Diamonds', 'Clubs', 'Spades']
cards_list = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King']
deck = [(card, category) for category in card_categories for card in cards_list]
def card_value(card):
  if card[0] in ['Jack', 'Queeen', 'King']:
    return 10
  elif card[0] == 'Ace':
    return 11
  else:
    return int(card[0])
random.shuffle(deck)
player_card = [deck.pop(), deck.pop()]
dealer_card = [deck.pop(), deck.pop()]
while True:
  player_score = sum(card_value(card) for card in player_card)
  dealer_score = sum(card_value(card) for card in dealer_card)
  print("Cards Player Has: ", player_card)
  print("Score Of The Player: ", player_score)
  print("\n")
  choice = input('What do you want? ["play" to request another card, "stop" to stop]: ').lower()
  if choice == "play":
    new_card = deck.pop()
    player_card.append(new_card)
  elif choice == "stop":
    break
  else:
    print("Invalid choice. Please try again.")
    continue
  if player_score > 21:
    print("Cards Dealer Has: ", dealer_card)
    print("Score Of The Dealer: ", dealer_score)
    print("Cards Player Has: ", player_card)
    print("Score Of The Player: ", player_score)
    print("Dealer wins(Player Loss Because Player score is exceeding 21)")
    break
  while dealer_score < 17:
    new_card = deck.pop()
    dealer_card.append(new_card)
    dealer_score += card_value(new_card)
  print("Cards Dealer Has: ", dealer_card)
  print("Score Of The Dealer: ", dealer_score)
  print("\n")
  if dealer_score > 21:
    print("Cards Dealer Has: ", dealer_card)
    print("Score Of The Dealer: ", dealer_score)
    print("Cards Player Has: ", player_card)
    print("Score Of The Player: ", player_score)
    print("Player wins(Dealer Loss Because Dealer score is exceeding 21)")
  elif player_score > dealer_score:
    print("Cards Dealer Has: ", dealer_card)
    print("Score Of The Dealer: ", dealer_score)
    print("Cards Player Has: ", player_card)
    print("Score Of The Player: ", player_score)
    print("Player wins (Player Has High Score than Dealer)")
  elif dealer_score > player_score:
    print("Cards Dealer Has: ", dealer_card)
    print("Score Of The Dealer: ", dealer_score)
    print("Cards Player Has: ", player_card)
    print("Score Of The Player: ", player_score)
    print("Dealer wins(Dealer Has High Score than Player)")
  else:
    print("Cards Dealer Has: ", dealer_card)
    print("Score Of The Dealer: ", dealer_score)
    print("Cards Player Has: ", player_card)
    print("Score Of The Player: ", player_score)
    print("It's a tie.")

Cards Player Has:  [('7', 'Clubs'), ('6', 'Spades')]
Score Of The Player:  13


What do you want? ["play" to request another card, "stop" to stop]: stop


In [ ]:
#40. Write a program that generates the prime factors of a given number using trial division

def TrialDivision(N):
  i = 2
  k = int(N ** 0.5)
  while(i <= k):
    if(N % i == 0):
      return 0
    i += 1
  return 1
if __name__ =='__main__':
  N = 49
  p = TrialDivision(N)
  if(p):
    print("Prime")
  else:
    print("Composite")

Composite
